version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    ports:
      - '80:80'
    restart: always

  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres_password
    image: 'postgres:latest'
      
  redis:
    image: 'redis:latest'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /usr/app/node_modules
      - ./api:/usr/app/

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
